spring.application.name=ecommerce
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=ashu
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true




# JwT
jwt.secret=a53d0efef84c82d4aa57ad99db9c5ab6233b04fae360106eff06293f5c7f8712
jwt.expiration=3600000

jwt.refreshSecret=fe4ef251102f2fbd878029f2acb1e99b59bf935d6970a08f8e933cfa182b9c90
jwt.refreshExpiration=86400000
jwt.tokenPrefix=Bearer



#cookie
cookie.expiration=86400000
cookie.name=refreshToken
cookie.path=/api/auth/
cookie.httpOnly=true
cookie.secure=true
cookie.sameSite=Strict